"""
Revision ID: 3bf1d402e0c2
Revises: 
Create Date: 2026-08-06 18:35:03.494721
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3bf1d402e0c2'
down_revision = None
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('query_hash', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_caches'))
    )
    op.create_index(op.f('ix_analytics_caches_id'), 'analytics_caches', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_caches_key'), 'analytics_caches', ['key'], unique=True)
    op.create_index(op.f('ix_analytics_caches_query_hash'), 'analytics_caches', ['query_hash'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('name', name=op.f('uq_districts_name'))
    )
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=False)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_target_year'), 'predictions', ['target_year'], unique=False)
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('college_code', sa.String(length=10), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_colleges_district_id_districts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colleges')),
    sa.UniqueConstraint('name', name=op.f('uq_colleges_name'))
    )
    op.create_index(op.f('ix_colleges_college_code'), 'colleges', ['college_code'], unique=True)
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('degree_level', sa.String(length=64), nullable=True),
    sa.Column('intake', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_courses_college_id_colleges'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_college_id'), 'courses', ['college_id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_candidates_course_id_courses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_table('cutoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('choice_code', sa.String(length=10), nullable=False),
    sa.Column('hu_open', sa.Float(), nullable=True),
    sa.Column('hu_sc', sa.Float(), nullable=True),
    sa.Column('hu_st', sa.Float(), nullable=True),
    sa.Column('hu_vjdt', sa.Float(), nullable=True),
    sa.Column('hu_ntb', sa.Float(), nullable=True),
    sa.Column('hu_ntc', sa.Float(), nullable=True),
    sa.Column('hu_ntd', sa.Float(), nullable=True),
    sa.Column('hu_obc', sa.Float(), nullable=True),
    sa.Column('hu_sebc', sa.Float(), nullable=True),
    sa.Column('ohu_open', sa.Float(), nullable=True),
    sa.Column('ohu_sc', sa.Float(), nullable=True),
    sa.Column('ohu_st', sa.Float(), nullable=True),
    sa.Column('ohu_vjdt', sa.Float(), nullable=True),
    sa.Column('ohu_ntb', sa.Float(), nullable=True),
    sa.Column('ohu_ntc', sa.Float(), nullable=True),
    sa.Column('ohu_ntd', sa.Float(), nullable=True),
    sa.Column('ohu_obc', sa.Float(), nullable=True),
    sa.Column('ohu_sebc', sa.Float(), nullable=True),
    sa.Column('ews', sa.Float(), nullable=True),
    sa.Column('tfws', sa.Float(), nullable=True),
    sa.Column('orphan', sa.Float(), nullable=True),
    sa.Column('pwd', sa.Float(), nullable=True),
    sa.Column('institute_level', sa.Float(), nullable=True),
    sa.Column('minority', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_cutoffs_college_id_colleges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_cutoffs_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cutoffs'))
    )
    op.create_index(op.f('ix_cutoffs_choice_code'), 'cutoffs', ['choice_code'], unique=False)
    op.create_index(op.f('ix_cutoffs_college_id'), 'cutoffs', ['college_id'], unique=False)
    op.create_index(op.f('ix_cutoffs_course_id'), 'cutoffs', ['course_id'], unique=False)
    op.create_index(op.f('ix_cutoffs_id'), 'cutoffs', ['id'], unique=False)
    op.create_index(op.f('ix_cutoffs_round'), 'cutoffs', ['round'], unique=False)
    op.create_index(op.f('ix_cutoffs_year'), 'cutoffs', ['year'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('recommendation', sa.String(length=2048), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_recommendations_college_id_colleges'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_recommendations_course_id_courses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_college_id'), 'recommendations', ['college_id'], unique=False)
    op.create_index(op.f('ix_recommendations_course_id'), 'recommendations', ['course_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('seat_matrices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('choice_code', sa.String(length=10), nullable=False),
    sa.Column('tfws_choice_code', sa.String(length=11), nullable=True),
    sa.Column('intake', sa.Integer(), nullable=True),
    sa.Column('hu_open', sa.Integer(), nullable=True),
    sa.Column('hu_sc', sa.Integer(), nullable=True),
    sa.Column('hu_st', sa.Integer(), nullable=True),
    sa.Column('hu_vjdt', sa.Integer(), nullable=True),
    sa.Column('hu_ntb', sa.Integer(), nullable=True),
    sa.Column('hu_ntc', sa.Integer(), nullable=True),
    sa.Column('hu_ntd', sa.Integer(), nullable=True),
    sa.Column('hu_obc', sa.Integer(), nullable=True),
    sa.Column('hu_sebc', sa.Integer(), nullable=True),
    sa.Column('ohu_open', sa.Integer(), nullable=True),
    sa.Column('ohu_sc', sa.Integer(), nullable=True),
    sa.Column('ohu_st', sa.Integer(), nullable=True),
    sa.Column('ohu_vjdt', sa.Integer(), nullable=True),
    sa.Column('ohu_ntb', sa.Integer(), nullable=True),
    sa.Column('ohu_ntc', sa.Integer(), nullable=True),
    sa.Column('ohu_ntd', sa.Integer(), nullable=True),
    sa.Column('ohu_obc', sa.Integer(), nullable=True),
    sa.Column('ohu_sebc', sa.Integer(), nullable=True),
    sa.Column('pwd_total', sa.Integer(), nullable=True),
    sa.Column('orphan', sa.Integer(), nullable=True),
    sa.Column('institute_level', sa.Integer(), nullable=True),
    sa.Column('minority', sa.Integer(), nullable=True),
    sa.Column('tfws_seats', sa.Integer(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_seat_matrices_college_id_colleges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_seat_matrices_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_matrices'))
    )
    op.create_index(op.f('ix_seat_matrices_choice_code'), 'seat_matrices', ['choice_code'], unique=False)
    op.create_index(op.f('ix_seat_matrices_college_id'), 'seat_matrices', ['college_id'], unique=False)
    op.create_index(op.f('ix_seat_matrices_course_id'), 'seat_matrices', ['course_id'], unique=False)
    op.create_index(op.f('ix_seat_matrices_id'), 'seat_matrices', ['id'], unique=False)
    op.create_index(op.f('ix_seat_matrices_round'), 'seat_matrices', ['round'], unique=False)
    op.create_index(op.f('ix_seat_matrices_year'), 'seat_matrices', ['year'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('choice_code', sa.String(length=10), nullable=True),
    sa.Column('tfws_choice_code', sa.String(length=11), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('hu_open', sa.Integer(), nullable=True),
    sa.Column('hu_sc', sa.Integer(), nullable=True),
    sa.Column('hu_st', sa.Integer(), nullable=True),
    sa.Column('hu_vjdt', sa.Integer(), nullable=True),
    sa.Column('hu_ntb', sa.Integer(), nullable=True),
    sa.Column('hu_ntc', sa.Integer(), nullable=True),
    sa.Column('hu_ntd', sa.Integer(), nullable=True),
    sa.Column('hu_obc', sa.Integer(), nullable=True),
    sa.Column('hu_sebc', sa.Integer(), nullable=True),
    sa.Column('ohu_open', sa.Integer(), nullable=True),
    sa.Column('ohu_sc', sa.Integer(), nullable=True),
    sa.Column('ohu_st', sa.Integer(), nullable=True),
    sa.Column('ohu_vjdt', sa.Integer(), nullable=True),
    sa.Column('ohu_ntb', sa.Integer(), nullable=True),
    sa.Column('ohu_ntc', sa.Integer(), nullable=True),
    sa.Column('ohu_ntd', sa.Integer(), nullable=True),
    sa.Column('ohu_obc', sa.Integer(), nullable=True),
    sa.Column('ohu_sebc', sa.Integer(), nullable=True),
    sa.Column('pwd_total', sa.Integer(), nullable=True),
    sa.Column('orphan', sa.Integer(), nullable=True),
    sa.Column('institute_level', sa.Integer(), nullable=True),
    sa.Column('minority', sa.Integer(), nullable=True),
    sa.Column('tfws_seats', sa.Integer(), nullable=True),
    sa.Column('total_vacancies', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_vacancies_college_id_colleges')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_vacancies_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancies'))
    )
    op.create_index(op.f('ix_vacancies_choice_code'), 'vacancies', ['choice_code'], unique=False)
    op.create_index(op.f('ix_vacancies_year'), 'vacancies', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_year'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_choice_code'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_seat_matrices_year'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_round'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_id'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_course_id'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_college_id'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_choice_code'), table_name='seat_matrices')
    op.drop_table('seat_matrices')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_course_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_college_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_cutoffs_year'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_round'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_id'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_course_id'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_college_id'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_choice_code'), table_name='cutoffs')
    op.drop_table('cutoffs')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_college_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_college_code'), table_name='colleges')
    op.drop_table('colleges')
    op.drop_index(op.f('ix_predictions_target_year'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_analytics_caches_query_hash'), table_name='analytics_caches')
    op.drop_index(op.f('ix_analytics_caches_key'), table_name='analytics_caches')
    op.drop_index(op.f('ix_analytics_caches_id'), table_name='analytics_caches')
    op.drop_table('analytics_caches')
    # ### end Alembic commands ###
