"""
Revision ID: 7c7875425cca
Revises: fc392829fb40
Create Date: 2026-07-29 17:22:41.940966
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7c7875425cca'
down_revision = 'fc392829fb40'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('query_hash', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_caches'))
    )
    op.create_index(op.f('ix_analytics_caches_id'), 'analytics_caches', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_caches_key'), 'analytics_caches', ['key'], unique=True)
    op.create_index(op.f('ix_analytics_caches_query_hash'), 'analytics_caches', ['query_hash'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('name', name=op.f('uq_districts_name'))
    )
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=False)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_target_year'), 'predictions', ['target_year'], unique=False)
    op.create_table('cutoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('cutoff_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_cutoffs_college_id_colleges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_cutoffs_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cutoffs'))
    )
    op.create_index(op.f('ix_cutoffs_category'), 'cutoffs', ['category'], unique=False)
    op.create_index(op.f('ix_cutoffs_college_id'), 'cutoffs', ['college_id'], unique=False)
    op.create_index(op.f('ix_cutoffs_course_id'), 'cutoffs', ['course_id'], unique=False)
    op.create_index(op.f('ix_cutoffs_id'), 'cutoffs', ['id'], unique=False)
    op.create_index(op.f('ix_cutoffs_year'), 'cutoffs', ['year'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('recommendation', sa.String(length=2048), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_recommendations_college_id_colleges'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_recommendations_course_id_courses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_college_id'), 'recommendations', ['college_id'], unique=False)
    op.create_index(op.f('ix_recommendations_course_id'), 'recommendations', ['course_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('seat_matrices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_seat_matrices_college_id_colleges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_seat_matrices_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_matrices'))
    )
    op.create_index(op.f('ix_seat_matrices_category'), 'seat_matrices', ['category'], unique=False)
    op.create_index(op.f('ix_seat_matrices_college_id'), 'seat_matrices', ['college_id'], unique=False)
    op.create_index(op.f('ix_seat_matrices_course_id'), 'seat_matrices', ['course_id'], unique=False)
    op.create_index(op.f('ix_seat_matrices_id'), 'seat_matrices', ['id'], unique=False)
    op.create_index(op.f('ix_seat_matrices_year'), 'seat_matrices', ['year'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_vacancies_college_id_colleges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_vacancies_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancies'))
    )
    op.create_index(op.f('ix_vacancies_college_id'), 'vacancies', ['college_id'], unique=False)
    op.create_index(op.f('ix_vacancies_course_id'), 'vacancies', ['course_id'], unique=False)
    op.create_index(op.f('ix_vacancies_id'), 'vacancies', ['id'], unique=False)
    op.create_index(op.f('ix_vacancies_year'), 'vacancies', ['year'], unique=False)
    op.drop_constraint(op.f('fk_candidates_college_id_colleges'), 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'college_id')
    op.drop_column('candidates', 'cutoff')
    op.add_column('colleges', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_colleges_district_id_districts'), 'colleges', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    op.drop_column('colleges', 'district')
    op.drop_column('colleges', 'university')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('university', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('district', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_colleges_district_id_districts'), 'colleges', type_='foreignkey')
    op.drop_column('colleges', 'district_id')
    op.add_column('candidates', sa.Column('cutoff', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_candidates_college_id_colleges'), 'candidates', 'colleges', ['college_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_vacancies_year'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_course_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_college_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_seat_matrices_year'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_id'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_course_id'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_college_id'), table_name='seat_matrices')
    op.drop_index(op.f('ix_seat_matrices_category'), table_name='seat_matrices')
    op.drop_table('seat_matrices')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_course_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_college_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_cutoffs_year'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_id'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_course_id'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_college_id'), table_name='cutoffs')
    op.drop_index(op.f('ix_cutoffs_category'), table_name='cutoffs')
    op.drop_table('cutoffs')
    op.drop_index(op.f('ix_predictions_target_year'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_analytics_caches_query_hash'), table_name='analytics_caches')
    op.drop_index(op.f('ix_analytics_caches_key'), table_name='analytics_caches')
    op.drop_index(op.f('ix_analytics_caches_id'), table_name='analytics_caches')
    op.drop_table('analytics_caches')
    # ### end Alembic commands ###
