"""
Revision ID: a723057ad4a7
Revises: 0001_initial
Create Date: 2026-07-29 17:04:13.828295
"""

from alembic import op
import sqlalchemy as sa
 
# revision identifiers, used by Alembic.
revision = 'a723057ad4a7'
down_revision = '0001_initial'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
